### ISSUE TITLE
divide by zero error

### ISSUE THREAD

**Issue by Razaekel** [flow/noise#6]
In modifiers/Curve.getValue(), there's a divide by zero error:

        // Compute the alpha value used for cubic interpolation.
        double input0 = controlPoints.get(indexPos).inputValue;
        double input1 = controlPoints.get(indexPos).inputValue;
        double alpha = (sourceModuleValue - input0) / (input1 - input0);

Because input0 = input1 since they're getting the same indexPos, input1 - input0 = 0, thus the divide by zero error.

It needs to be replaced with the following:

        // Compute the alpha value used for cubic interpolation.
        double input0 = controlPoints.get(index1).inputValue;
        double input1 = controlPoints.get(index2).inputValue;
        double alpha = (sourceModuleValue - input0) / (input1 - input0);

**Comment by Zidane** [comment]
@DDoS 

This sounds like right up your alley.
