### ISSUE TITLE
Detach fork relationship from jlibnoise

### ISSUE THREAD

**Issue by gratimax** [flow/noise#8]
With PR #5, flow noise will look less and less similar its parent, jlibnoise. The only similarity would be several commits early in history, meaning that the "forked from" label is not really necessary. The last commit to jlibnoise was in August 2013, meaning that flow noise has become its spritual successor, and its own project.

Removing the "fork" relationship to jlibnoise allows a few other perks, like [searching code](https://github.com/flow/noise/search?q=module&type=Code).

This can be done, [as explained by Github](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork):

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub support](https://github.com/contact).

**Comment by lukespragg** [comment]
I've sent the request.

**Comment by lukespragg** [comment]
Done!
